<?php
/*
 * Copyright © 2022 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Rejoiner\Acr\Block\Base $block */
$rejoinerHelper = $block->getRejoinerHelper();
// Need to render blocks one by one to implode them into the single JSON
$childBlockNames = $block->getChildNames();
$childBlocksHtml = [];
foreach ($childBlockNames as $childBlockName) {
    if ($html = $block->getChildHtml($childBlockName, false)) {
        $childBlocksHtml[] = $html;
    }
}
?>
<?php if ($rejoinerHelper->getRejoinerSiteId() && $rejoinerHelper->getDomain()): ?>
    <?php
    $domain = $block->escapeHtml($rejoinerHelper->getDomain());
    $siteId = $block->escapeHtml($rejoinerHelper->getRejoinerSiteId());
    $rejoinerScriptUri = $block->escapeHtml($rejoinerHelper->getRejoinerScriptUri());
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "RejoinerAcrTracking": {
                    "rejoinerSiteId"          : "<?= $siteId; ?>",
                    "rejoinerDomain"          : "<?= $domain; ?>",
                    "rejoinerScriptUri"       : "<?= $rejoinerScriptUri; ?>",
                    "trackNumberEnabled"      : <?= $rejoinerHelper->getTrackNumberEnabled(); ?>,
                    "persistFormsEnabled"     : <?= $rejoinerHelper->getPersistFormsEnabled(); ?>,
                    "trackCartDataOnThisPage" : <?= $rejoinerHelper->getShoppingCartDataOnThisPage() ?><?= (!empty($childBlocksHtml))? ',' : ''?>
                    <?= implode(',', $childBlocksHtml); ?>
                }
            }
        }
    </script>
<?php endif ?>

