<?php
/**
 * @var Base $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Rejoiner\Acr\Block\Base;

?>
<?php
$rejoinerHelper = $block->getRejoinerHelper();
// Need to render blocks one by one to implode them into the single JSON
$childBlockNames = $block->getChildNames();
$childBlocksHtml = [];

foreach ($childBlockNames as $childBlockName) {
    if ($html = $block->getChildHtml($childBlockName, false)) {
        $childBlocksHtml[] = $html;
    }
}
?>
<?php if ($rejoinerHelper->getRejoinerSiteId() && $rejoinerHelper->getDomain()) : ?>
    <?php
    $domain = $escaper->escapeHtml($rejoinerHelper->getDomain());
    $siteId = $escaper->escapeHtml($rejoinerHelper->getRejoinerSiteId());
    $rejoinerScriptUri = $escaper->escapeHtml($rejoinerHelper->getRejoinerScriptUri());
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "RejoinerAcrTracking": {
                    "rejoinerSiteId"          : "<?= $siteId ?>",
                    "rejoinerDomain"          : "<?= $domain ?>",
                    "rejoinerScriptUri"       : "<?= $rejoinerScriptUri ?>",
                    "trackNumberEnabled"      : <?= $escaper->escapeHtml($rejoinerHelper->getTrackNumberEnabled()) ?>,
                    "persistFormsEnabled"     : <?= $escaper->escapeHtml($rejoinerHelper->getPersistFormsEnabled()) ?>,
                    "trackCartDataOnThisPage" : <?=
                        $escaper->escapeHtml($rejoinerHelper->getShoppingCartDataOnThisPage())
                    ?><?php echo (!empty($childBlocksHtml))? ',': ''?>
                    <?= /** @noEscape  */ implode(',', $childBlocksHtml) ?>
                }
            }
        }
    </script>
<?php endif ?>

