<?php
/**
 * Copyright © 2016 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Rejoiner\Acr\Block\Snippets
 */
$rejoinerHelper = $block->getRejoinerHelper() ?>
<script type="text/x-magento-init">
    {
        "*": {
            "RejoinerAcrConversion": {
                "rejoinerSiteId"      : "<?php echo $rejoinerHelper->getRejoinerSiteId() ?>",
                "rejoinerDomain"      : "<?php echo $rejoinerHelper->getDomain() ?>"
            }
        }
    }
</script>
