<?php
/**
 * Copyright © 2016 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Rejoiner\Acr\Block\Snippets
 */
$rejoinerHelper = $block->getRejoinerHelper();
?>
<?php if ($rejoinerHelper->getRejoinerSiteId() && $rejoinerHelper->getDomain() && $block->getCartItems()): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "RejoinerAcrTracking": {
                    "rejoinerSiteId"      : "<?php echo $rejoinerHelper->getRejoinerSiteId(); ?>",
                    "rejoinerDomain"      : "<?php echo $rejoinerHelper->getDomain(); ?>",
                    "trackNumberEnabled"  : "<?php echo $rejoinerHelper->getTrackNumberEnabled(); ?>",
                    "persistFormsEnabled" : "<?php echo $rejoinerHelper->getPersistFormsEnabled(); ?>",
                    "cartData"            : <?php echo $block->getCartData(); ?>,
                    "cartItems"           : <?php echo $block->getJsonHelper()->jsonEncode($block->getCartItems()); ?>,
                    "removedItems"        : <?php echo $block->getJsonHelper()->jsonEncode($rejoinerHelper->checkRemovedItem()); ?>
                }
            }
        }
    </script>
<?php endif; ?>

