<?php
/*
 * Copyright © 2022 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Rejoiner\Acr\Block\Newsletter $block */
?>
<?php if ($block->isEnabled()): ?>
    <?php if ($block->showOnLoginCheckout()): ?>
    <div class="field choice newsletter">
        <input
                type="checkbox"
                name="is_subscribed"
                title="<?= $block->escapeHtmlAttr($block->getLabel()) ?>"
                value="1"
                id="is_subscribed"
                class="checkbox"
                <?= $block->shouldBeCheckedByDefault() ? 'checked="checked"' : '' ?>
        />
        <label for="is_subscribed" class="label"><span><?= $block->escapeHtml($block->getLabel()) ?></span></label>
    </div>
    <?php endif; ?>
<?php endif; ?>
