<?php
/**
 * Copyright © 2017 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var Newsletter $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Rejoiner\Acr\Block\Newsletter;

?>
<?php if ($block->isEnabled()): ?>
    <?php if ($block->showOnLoginCheckout()): ?>
    <div class="field choice newsletter">
        <input
                type="checkbox"
                name="is_subscribed"
                title="<?= $escaper->escapeHtmlAttr($block->getLabel()); ?>"
                value="1"
                id="is_subscribed"
                class="checkbox"
                <?php echo $block->shouldBeCheckedByDefault() ? 'checked="checked"' : ''; ?>
        />
        <label for="is_subscribed" class="label"><span><?= $escaper->escapeHtml($block->getLabel()); ?></span></label>
    </div>
    <?php endif; ?>
<?php endif; ?>
