<?php
/**
 * Copyright © 2017 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var Newsletter $block
 * @var Escaper $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Rejoiner\Acr\Block\Newsletter;

?>
<?php if ($block->isEnabled()): ?>
<?php
$jsonConfig = /* @escapeNotVerified */ json_encode($block->getConfig());
$checkboxSelector = $escaper->escapeHtml($block->getCheckboxSelectors());
$label = $escaper->escapeHtmlAttr($block->getLabel());
$cssClass = $escaper->escapeHtmlAttr($block->getCssClass());
$labelChanged = '';

if ($block->isLabelChanged()) {
    $labelChanged = <<<labelChanged
    if (label) {
        \$labels.text(label);
    }

    \$labels.show();
labelChanged;
}

$scriptString = <<<script
    window.rejoinerMarketing = $jsonConfig;

    require([
        'jquery'
    ], function($) {
        var \$checkboxes = $('$checkboxSelector'),
            \$labels = \$checkboxes.siblings('label'),
            label = '$label',
            cssClass = '$cssClass';

        if (\$checkboxes.length) {
            if (cssClass) {
                \$checkboxes.addClass(cssClass);
            }

            $labelChanged
        }
    });
script;
?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php endif; ?>
