<?php
/*
 * Copyright © 2022 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var \Rejoiner\Acr\Block\Newsletter $block */
?>
<?php if ($block->isEnabled()): ?>
    <script>
        window.rejoinerMarketing = <?= /* @escapeNotVerified */ \Zend_Json::encode($block->getConfig()); ?>;

        require([
            'jquery'
        ], function($) {
            var $checkboxes = $('<?= $block->getCheckboxSelectors() ?>'),
                $labels = $checkboxes.siblings('label'),
                label = '<?= $block->getLabel() ?>',
                cssClass = '<?= $block->getCssClass() ?>';

            if ($checkboxes.length) {
                if (cssClass) {
                    $checkboxes.addClass(cssClass);
                }

                <?php if ($block->isLabelChanged()): ?>
                    if (label) {
                        $labels.text(label);
                    }

                    $labels.show();
                <?php endif; ?>
            }
        });
    </script>
<?php endif; ?>
