<?php
/**
 * Copyright © 2017 Rejoiner. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var Newsletter $block
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;
use Rejoiner\Acr\Block\Newsletter;

?>
<?php if ($block->isEnabled()): ?>
    <style>
        <?php if ($styles = $block->getStyles()): ?>
            <?= $escaper->escapeHtml($block->getCheckboxSelectors()) ?> {<?= $escaper->escapeHtml($styles) ?>}
        <?php endif; ?>

        <?php if ($block->isLabelChanged()): ?>
            body .page-wrapper #maincontent .newsletter [name=is_subscribed] + label,
            body .page-wrapper #maincontent .form-newsletter-manage #subscription + label { display: none; }
        <?php endif; ?>

        <?php if ($block->hideInCustomerAccount()): ?>
            .account .form-newsletter-manage { display: none !important; }
        <?php endif; ?>
    </style>
<?php endif; ?>
